### 1. What is NumPy?
NumPy (Numerical Python) is a powerful Python library used for numerical computations. It
provides support for large, multi-dimensional arrays and matrices, along with a collection of
mathematical functions to operate on these arrays efficiently. NumPy is widely used in
scientific computing, data analysis, machine learning, and AI applications.
NumPy is an essential library for numerical computations in Python. Its efficiency, speed, and
ease of use make it indispensable for data science, AI, and scientific computing. Whether
you're working with large datasets, complex mathematical functions, or machine learning
models, NumPy is the go-to tool.

### 2. Why Do We Need NumPy?
1. Efficient Computation
- NumPy is significantly faster than Python lists because it uses C and Fortran under the hood.
- It provides optimized vectorized operations that eliminate the need for loops innumerical computations.
2. Memory Efficiency
- NumPy arrays consume less memory compared to Python lists due to their fixed data type and efficient storage.
3. Multi-Dimensional Arrays (ndarray)
- NumPy supports n-dimensional arrays, making it useful for handling matrices and tensor operations.
4. Broadcasting
- It allows arithmetic operations on arrays of different shapes without explicitly reshaping them.
5. Built-in Mathematical Functions
- Includes a vast range of mathematical functions like sin(), cos(), log(), mean(), std(), etc.
6. Integration with Other Libraries
- NumPy is the foundation of many data science and AI libraries, such as Pandas, SciPy, TensorFlow, and PyTorch.

### 3. Creating Arrays

In [6]:
import numpy as np

# Creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Creating a 2D array
arr3 = np.array([[1, 2, 3,4,5]])
print(arr3)

# Creating a 2D array
arr4 = np.array([[1], [2], [3],[4],[5]])
print(arr4)

# Creating a 3D array
arr5 = np.array([[[1, 2, 3], [4, 5, 6]], 
                 [[11, 22, 33], [44, 55, 66]],
                 [[111, 222, 333], [444, 555, 666]]])
print(arr5)

# Creating a 3D array
arr6 = np.array([[[[1, 2, 3], [4, 5, 6]], 
                 [[11, 22, 33], [44, 55, 66]],
                 [[111, 222, 333], [444, 555, 666]]],

                 [[[1, 2, 3], [4, 5, 6]], 
                 [[11, 22, 33], [44, 55, 66]],
                 [[111, 222, 333], [444, 555, 666]]]])
print(arr6)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[[[  1   2   3]
  [  4   5   6]]

 [[ 11  22  33]
  [ 44  55  66]]

 [[111 222 333]
  [444 555 666]]]
[[[[  1   2   3]
   [  4   5   6]]

  [[ 11  22  33]
   [ 44  55  66]]

  [[111 222 333]
   [444 555 666]]]


 [[[  1   2   3]
   [  4   5   6]]

  [[ 11  22  33]
   [ 44  55  66]]

  [[111 222 333]
   [444 555 666]]]]


### 4. Array Properties

In [7]:
print(arr1.shape)
print(arr1.size)
print(arr1.dtype)

print(arr2.shape)
print(arr2.size)
print(arr2.dtype)

print(arr3.shape)
print(arr3.size)
print(arr3.dtype)

print(arr4.shape)
print(arr4.size)
print(arr4.dtype)

print(arr5.shape)
print(arr5.size)
print(arr5.dtype)

print(arr6.shape)
print(arr6.size)
print(arr6.dtype)


(5,)
5
int64
(2, 3)
6
int64
(1, 5)
5
int64
(5, 1)
5
int64
(3, 2, 3)
18
int64
(2, 3, 2, 3)
36
int64


### 5. Special Arrays

In [52]:
np.zeros((3, 3)) # 3x3 matrix filled with zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [53]:
np.ones((2, 2)) # 2x2 matrix filled with ones

array([[1., 1.],
       [1., 1.]])

In [54]:
np.eye(3) # Identity matrix of size 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
np.arange(0, 10, 2) # Array from 0 to 10 with step 2

array([0, 2, 4, 6, 8])

In [56]:
np.linspace(1, 5, 10) # 10 values between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

### 6. Mathematical Operations

In [57]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b) # Element-wise addition
print(a - b) # Element-wise subtraction
print(a * b) # Element-wise multiplication
print(a / b) # Element-wise division
print(np.dot(a, b)) # Dot product

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
32


### 7. Array Reshaping

In [58]:
arr = np.arange(1,10)
print(arr)
reshaped = arr.reshape(3, 3) # Reshapes 1D array into 3x3 matrix
print(reshaped)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### 8. Indexing & Slicing

In [59]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1]) # 20 (Indexing)
print(arr[1:4]) # [20, 30, 40] (Slicing), from index 1 to 4 (exclude)

20
[20 30 40]


### 9. Aggregation Functions

Mean: $ \mu = \frac{1}{n} \sum_{i=1}^{n} x_i $

Standard Deviation: $ \sigma = \sqrt{ \frac{1}{n} \sum_{i=1}^{n} (x_i - \mu)^2 } $

| Symbol             | Meaning                       |
| ------------------ | ----------------------------- |
| $x_i$              | Data point                    |
| $\mu$ or $\bar{x}$ | Mean of the data              |
| $n$                | Number of data points         |
| $\sigma$           | Population standard deviation |

In [60]:
arr = np.array([1,2,3,4,5,6,7,8])
sum = np.sum(arr)
print("Sum =",sum)
print("Mean =", np.mean(arr))
print("Standard Deviation =", np.std(arr))
print("Max =", np.max(arr))
print("Min ",np.min(arr))

Sum = 36
Mean = 4.5
Standard Deviation = 2.29128784747792
Max = 8
Min  1


### 10. Random Numbers

In [61]:
np.random.rand(3,4)  # 3x4 matrix of random numbers between 0 and 1

array([[0.14639987, 0.68645279, 0.51286105, 0.09780833],
       [0.54896893, 0.52320524, 0.88995804, 0.77992529],
       [0.24384942, 0.93221969, 0.97524984, 0.08051352]])

In [62]:
np.random.randint(1,100,(3,3)) # # 3x3 matrix of random integers from 1 to 100

array([[48, 72, 67],
       [79, 31, 64],
       [17, 31, 45]])

### 11. Why Do We Need NumPy Arrays Instead of Python Lists or Standard Python Sequences?
Python lists are flexible and easy to use, but they have significant performance and memory
limitations when dealing with large numerical computations. NumPy arrays (ndarray) are
optimized for performance, memory efficiency, and numerical operations, making them a
superior choice for numerical and scientific computing.

##### 1. Performance: NumPy is Faster than Python Lists
Reason: NumPy Uses Optimized C Implementations
NumPy operations are implemented in C and Fortran, which makes them significantly faster
than Python lists, which are dynamically typed and interpreted at runtime.

Example: Speed Comparison
Let's compare the speed of NumPy arrays and Python lists for an element-wise multiplication
operation.

In [63]:
import numpy as np
import time
# Creating large lists and arrays
size = 10000000
py_list1 = list(range(size))
py_list2 = list(range(size))

np_array1 = np.arange(size)
np_array2 = np.arange(size)

# Timing Python list multiplication
start = time.time()
py_result = [x * y for x, y in zip(py_list1, py_list2)]
end = time.time()
print("Python List Time:", end - start)

# Timing NumPy array multiplication
start = time.time()
np_result = np_array1 * np_array2 # Vectorized operation
end = time.time()
print("NumPy Array Time:", end - start)

# Result: NumPy is typically 10-100x faster than Python lists for large operations.

Python List Time: 0.6797261238098145
NumPy Array Time: 0.07065796852111816


##### 2. Memory Efficiency: NumPy Uses Less Memory

Reason: NumPy Stores Data More Compactly

Python lists store elements as objects, which introduce extra overhead. NumPy arrays store
elements as contiguous blocks of memory with fixed data types, making them more space-
efficient.

Example: Memory Usage Comparison

In [64]:
import sys
size = 1000

# Python list memory consumption
py_list = list(range(size))
sum_size = sys.getsizeof(py_list) 
for i in py_list:
    sum_size = sum_size + sys.getsizeof(i)
print("Python List Memory (bytes):",sum_size)

# NumPy array memory consumption
np_array = np.arange(size)
print("NumPy Array Memory (bytes):", np_array.nbytes)

#Result: NumPy arrays consume significantly less memory than Python lists.


Python List Memory (bytes): 36052
NumPy Array Memory (bytes): 8000


##### 3. Broadcasting: Element-wise Operations Without Loops

Reason: NumPy Supports Vectorized Operations

In Python lists, operations require explicit loops or list comprehensions, while NumPy arrays
perform operations in a vectorized manner (applied to all elements simultaneously).

Example: Python List vs. NumPy Array Operations

In [65]:
# Using Python lists (Requires a loop)
py_list = [1, 2, 3, 4, 5]
py_result = [x * 2 for x in py_list] # Requires explicit iteration

# Using NumPy (No loop required)
np_array = np.array([1, 2, 3, 4, 5])
np_result = np_array * 2 # Vectorized operation

#Result: NumPy code is cleaner, shorter, and faster.

##### 4. Multi-Dimensional Data Handling
Reason: NumPy Supports Multi-Dimensional Arrays (ndarray)

Python lists require nested lists to represent matrices, making indexing and operations
cumbersome. NumPy provides n-dimensional arrays (ndarray), allowing for efficient
matrix operations.

Example: 2D Matrix Operations

In [66]:
# Python list (Nested list representation)
py_matrix = [[1, 2, 3], [4, 5, 6]]
py_matrix_transpose = [[py_matrix[j][i] for j in range(2)] for i in range(3)] # Manual transpose

# NumPy (Direct operations)
np_matrix = np.array([[1, 2, 3], [4, 5, 6]])
np_transpose = np_matrix.T # Transpose

#Result: NumPy allows built-in, optimized matrix operations, avoiding manual loops.

##### 5. Built-in Mathematical Functions
Reason: NumPy Provides Extensive Mathematical Functions

Python lists require manual implementations or math/statistics modules, while NumPy offers
efficient built-in functions.

Example: Computing Mean and Standard Deviation

In [67]:
import statistics
py_list = [1, 2, 3, 4, 5]

# Using Python's statistics module
py_mean = statistics.mean(py_list)
py_std = statistics.stdev(py_list)

# Using NumPy (Optimized)
np_array = np.array([1, 2, 3, 4, 5])
np_mean = np_array.mean()
np_std = np_array.std()

print("Python Mean:", py_mean, " NumPy Mean:", np_mean)
print("Python Std Dev:", py_std, " NumPy Std Dev:", np_std)

Python Mean: 3  NumPy Mean: 3.0
Python Std Dev: 1.5811388300841898  NumPy Std Dev: 1.4142135623730951


##### 6. Advanced Operations: Linear Algebra & Random Number Generation
NumPy provides:
- Linear Algebra (e.g., matrix multiplication, eigenvalues, determinants)
- Random Number Generation (e.g., normal distribution, uniform distribution)
- Fourier Transforms & Signal Processing

Example: Matrix Multiplication

In [68]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
# Matrix multiplication
C = np.dot(A, B)
print(C)

[[19 22]
 [43 50]]


##### 7. Vectorization in NumPy
Vectorization is a technique in NumPy that allows operations to be applied to entire arrays
(vectors) at once, without the need for explicit loops. This is possible because NumPy
executes operations in compiled C code under the hood, making them significantly faster
and more efficient than using Python loops.

Why Use Vectorization?
1. Faster Execution:
2. Simpler Code:
3. Memory Efficient:
4. Parallel Execution:
- NumPy operations run in optimized C code, avoiding Python's slow loops.
- No need for “for” loops or list comprehensions.
- NumPy arrays use contiguous memory blocks, reducing overhead.
- Takes advantage of SIMD (Single Instruction Multiple Data) processing.

Example: Without vs. With Vectorization

In [70]:
# Using Python Loops (Slow)
import time
# Creating large arrays
size = 10**6
py_list1 = list(range(size))
py_list2 = list(range(size))

start = time.time()
result = [x * y for x, y in zip(py_list1, py_list2)] # Loop-based multiplication
end = time.time()
print("Python Loop Time:", end - start)

#Using NumPy Vectorization (Fast)
import numpy as np
np_array1 = np.arange(size)
np_array2 = np.arange(size)
start = time.time()
result = np_array1 * np_array2 # Vectorized multiplication
end = time.time()
print("NumPy Vectorization Time:", end - start)

#Result: NumPy's vectorized operations can be 10-100x faster than using Python loops!

Python Loop Time: 0.04154491424560547
NumPy Vectorization Time: 0.006979942321777344


##### 8. Broadcasting in NumPy

What is Broadcasting?
Broadcasting is a feature in NumPy that allows operations between arrays of different
shapes without the need for explicit loops or reshaping. Instead of manually adjusting array
dimensions, NumPy automatically expands smaller arrays so that element-wise operations
can be performed efficiently.

Why is Broadcasting Useful?
- Avoids Explicit Loops → Faster execution
- Memory Efficient → No unnecessary copies of arrays
- Simplifies Code → Cleaner and more readable

Broadcasting Rules
For NumPy to perform broadcasting, it follows three simple rules to match array shapes:
- If the dimensions are different, NumPy automatically adds missing dimensions to the smaller array (left-padding with 1s).
- If one dimension is 1, NumPy stretches it to match the other dimension.
- If dimensions are incompatible (neither is 1 and they are different), an error occurs.

Examples of Broadcasting

Scalar and Array Broadcasting

In [72]:
import numpy as np
arr = np.array([1, 2, 3]) # Shape: (3,)
scalar = 10 # Shape: ()
result = arr + scalar # Broadcasting applies here
print(result) # [11 12 13]

# NumPy automatically expands scalar to match arr.
# Shape transformation: (3,) + () → (3,)

[11 12 13]
